const ROOMS_CREATE_ROOM_START = 'ROOMS_CREATE_ROOM_START';
const ROOMS_CREATE_ROOM_SUCCESS = 'ROOMS_CREATE_ROOM_SUCCESS';
const ROOMS_CREATE_ROOM_FAILURE = 'ROOMS_CREATE_ROOM_FAILURE';


const types = {
    ROOMS_CREATE_ROOM_START,
    ROOMS_CREATE_ROOM_SUCCESS,
    ROOMS_CREATE_ROOM_FAILURE,
}

export default types;