const ROOMS_CREATE_ROOM_START = 'ROOMS_CREATE_ROOM_START';
const ROOMS_CREATE_ROOM_SUCCESS = 'ROOMS_CREATE_ROOM_SUCCESS';
const ROOMS_CREATE_ROOM_FAILURE = 'ROOMS_CREATE_ROOM_FAILURE';
const ROOMS_CHANGE_ROOM_YOU_ARE_IN_DATA = 'ROOMS_CHANGE_ROOM_YOU_ARE_IN_DATA'
const ROOMS_GET_ROOMS_FROM_DATA_BASE_START = 'ROOMS_GET_ROOMS_FROM_DATA_BASE_START'
const ROOMS_GET_ROOMS_FROM_DATA_BASE_SUCCESS = 'ROOMS_GET_ROOMS_FROM_DATA_BASE_SUCCESS'
const ROOMS_GET_ROOMS_FROM_DATA_BASE_FAILURE = 'ROOMS_GET_ROOMS_FROM_DATA_BASE_FAILURE'


const types = {
    ROOMS_CREATE_ROOM_START,
    ROOMS_CREATE_ROOM_SUCCESS,
    ROOMS_CREATE_ROOM_FAILURE,
    ROOMS_CHANGE_ROOM_YOU_ARE_IN_DATA,
    ROOMS_GET_ROOMS_FROM_DATA_BASE_START,
    ROOMS_GET_ROOMS_FROM_DATA_BASE_SUCCESS,
    ROOMS_GET_ROOMS_FROM_DATA_BASE_FAILURE
}

export default types;