const USERS_POST_USER_START = 'USERS_POST_USER_START';
const USERS_POST_USER_SUCCESS = 'USERS_POST_USER_SUCCESS';
const USERS_POST_USER_FAILURE = 'USERS_POST_USER_FAILURE';
const USERS_LOGIN_START = 'USERS_LOGIN_START';
const USERS_LOGIN_SUCCESS = 'USERS_LOGIN_SUCCESS';
const USERS_LOGIN_FAILURE = 'USERS_LOGIN_FAILURE';
const USERS_GET_ALL_USERS_START = 'USERS_GET_ALL_USERS_START';
const USERS_GET_ALL_USERS_SUCCESS = 'USERS_GET_ALL_USERS_SUCCESS';
const USERS_GET_ALL_USERS_FAILURE = 'USERS_GET_ALL_USERS_FAILURE';
const USERS_SET_YOUR_DATA = 'USERS_SET_YOUR_DATA';
const USERS_CHANGE_NICKNAME_TAKEN_VALUE = 'USERS_CHANGE_NICKNAME_TAKEN_VALUE';
const USERS_CHANGE_TOO_MANY_ROOMS_VALUE = "USERS_CHANGE_TOO_MANY_ROOMS_VALUE";
const USERS_CHANGE_YOUR_ROOMS_NUMBER = 'USERS_CHANGE_YOUR_ROOMS_NUMBER'

const types = {
    USERS_POST_USER_START,
    USERS_POST_USER_SUCCESS,
    USERS_POST_USER_FAILURE,
    USERS_LOGIN_START,
    USERS_LOGIN_SUCCESS,
    USERS_LOGIN_FAILURE,
    USERS_GET_ALL_USERS_START,
    USERS_GET_ALL_USERS_SUCCESS,
    USERS_GET_ALL_USERS_FAILURE,
    USERS_SET_YOUR_DATA,
    USERS_CHANGE_NICKNAME_TAKEN_VALUE,
    USERS_CHANGE_TOO_MANY_ROOMS_VALUE,
    USERS_CHANGE_YOUR_ROOMS_NUMBER
}

export default types;